### ISSUE TITLE
MGS 2: Codec Static and other scaling issues

### ISSUE THREAD

**Issue by kite1234567** [ShizCalev/MGSHDFix#8] opened 2023-10-28 01:08 UTC
everything looks great now . the only thing noticed so far is the codec calls static overlay for their faces.

**Comment by TerrorThrills** [comment] 2023-10-28 01:24
Just to add an image. The static  and random image appear to be rendering in a lower resolution that in previous versions

![image](https://github.com/Lyall/MGSHDFix/assets/137555995/dd1f1bb8-8f11-4ac4-8f18-8c239849de18)

**Comment by TerrorThrills** [comment] 2023-10-28 01:25
Just to add an image. It appears the photo flash layer and static are both being rendered at a lower resolution the previous versions


![20231028020325_1](https://github.com/Lyall/MGSHDFix/assets/137555995/8f9216e7-bc70-47e9-b8ed-68bf3a9448fd)

**Comment by kite1234567** [comment] 2023-10-28 01:29
https://i.gyazo.com/6a994fba081561afb22478ecaabca8cd.gif heres another strange one.
its not too bad but the scent of the c4 on the radar is offset

**Comment by kite1234567** [comment] 2023-10-28 02:11
seems to be the same with water as well as bomb scent

**Comment by Blackbird88** [comment] 2023-10-29 14:00
Codec was fixed in MGSResolutionPatch so it's possible
https://github.com/Sergeanur/MGSResolutionPatch/commit/b9adc9af2c08bb6f5342bd5ce3f5729758ac4d49

**Comment by Lyall** [comment] 2023-10-29 20:23
This latest release (v0.7) should help with the codec issues. I don't know if the later issues shown here like the minimap bomb scent/water are fixed so it would be good to get some feedback.

**Comment by TerrorThrills** [comment] 2023-10-29 22:23
I htink those effects are natural to the game as the bomb location and water indicators are rendered at a higher y axis than the map. You would probably need to someone to test on the HD collection in order to verify that.

**Comment by kite1234567** [comment] 2023-10-29 22:27
> I htink those effects are natural to the game as the bomb location and water indicators are located at a higher y axis than the map. You would probably need to someone to test on the HD collection in order to verify that.

 It’s never been that way across any version the axis y axis doesn’t matter since the map is orthographic

**Comment by Lyall** [comment] 2023-10-29 22:37
On that note, if the other issues like the bomb scent etc are still there, uploading a save game with it would be very handy for testing.

**Comment by Lyall** [comment] 2023-10-30 14:02
> > On that note, if the other issues like the bomb scent etc are still there, uploading a save game with it would be very handy for testing.
> 
> im not home or i would do it, have you considered the dev mod to just warp to that location? https://www.nexusmods.com/metalgearsolidmastercollection/mods/1

That's a good shout. I tried that and loaded up the water part and it seems to render okay now.

Vanilla
https://github.com/Lyall/MGSHDFix/assets/695941/f396d558-e0b0-4e9b-b887-b9270d4ecb0f

MGSHDFix v0.7
https://github.com/Lyall/MGSHDFix/assets/695941/2f89286d-75b8-4ce0-a5ca-31c0adc72e45

**Comment by kite1234567** [comment] 2023-10-31 02:37
> > > On that note, if the other issues like the bomb scent etc are still there, uploading a save game with it would be very handy for testing.
> > 
> > 
> > im not home or i would do it, have you considered the dev mod to just warp to that location? https://www.nexusmods.com/metalgearsolidmastercollection/mods/1
> 
> That's a good shout. I tried that and loaded up the water part and it seems to render okay now.
> 
> Vanilla https://github.com/Lyall/MGSHDFix/assets/695941/f396d558-e0b0-4e9b-b887-b9270d4ecb0f
> 
> MGSHDFix v0.7 https://github.com/Lyall/MGSHDFix/assets/695941/2f89286d-75b8-4ce0-a5ca-31c0adc72e45
> 
> Edit: Bomb scent
> 
> Vanilla https://github.com/Lyall/MGSHDFix/assets/695941/85fbf8e8-30e0-4489-9ad6-b066abd40d2d
> 
> MGSHDFix v0.7 https://github.com/Lyall/MGSHDFix/assets/695941/3da4e918-e4f9-4f19-8914-67ef8a800ad4

huh it looks good on a horizontal axis but i think its still pretty wonky vertically. either way this is more than exceptional thanks for all this work.

**Comment by ConnorBarr** [comment] 2023-10-31 05:10
> > > > On that note, if the other issues like the bomb scent etc are still there, uploading a save game with it would be very handy for testing.
> > > 
> > > 
> > > im not home or i would do it, have you considered the dev mod to just warp to that location? https://www.nexusmods.com/metalgearsolidmastercollection/mods/1
> > 
> > 
> > That's a good shout. I tried that and loaded up the water part and it seems to render okay now.
> > Vanilla https://github.com/Lyall/MGSHDFix/assets/695941/f396d558-e0b0-4e9b-b887-b9270d4ecb0f
> > MGSHDFix v0.7 https://github.com/Lyall/MGSHDFix/assets/695941/2f89286d-75b8-4ce0-a5ca-31c0adc72e45
> > Edit: Bomb scent
> > Vanilla https://github.com/Lyall/MGSHDFix/assets/695941/85fbf8e8-30e0-4489-9ad6-b066abd40d2d
> > MGSHDFix v0.7 https://github.com/Lyall/MGSHDFix/assets/695941/3da4e918-e4f9-4f19-8914-67ef8a800ad4
> 
> huh it looks good on a horizontal axis but i think its still pretty wonky vertically. either way this is more than exceptional thanks for all this work.

I've just ran both sets of videos in Nvidia ICAT, the videos follow the exact same path  so i can't guarantee 100% but it looks correct to me.

**Comment by Lyall** [comment] 2023-11-01 00:12
> huh it looks good on a horizontal axis but i think its still pretty wonky vertically. either way this is more than exceptional thanks for all this work.

Check out [this footage](https://youtu.be/MkzO6DbDh0Q?t=8197) of the PS3 version being played, I've timestamped the same bomb scent area. It looks to match up to my eyes.

You're right though that it does look "off" but as you can see that's how it looks in the HD collection. Maybe it looked different in the PS2 original?

**Comment by ConnorBarr** [comment] 2023-11-01 01:13
> > huh it looks good on a horizontal axis but i think its still pretty wonky vertically. either way this is more than exceptional thanks for all this work.
> 
> Check out [this footage](https://youtu.be/MkzO6DbDh0Q?t=8197) of the PS3 version being played, I've timestamped the same bomb scent area. It looks to match up to my eyes.
> 
> You're right though that it does look "off" but as you can see that's how it looks in the HD collection. Maybe it looked different in the PS2 original?

I think your right this might have been a difference between the HD collection and the PS2. Here is a video of the game in PCSX2, It seems to be completly static unlike the PS3 Collection.

Here is a link to the PCSX2 Footage (20:46): https://www.youtube.com/watch?v=-lEYdMRIqBA
I also found this footage which follows the same behaviour as above but i cant find what platfrom its on: https://www.youtube.com/watch?v=xdF-LGiTsB0

**Comment by Lyall** [comment] 2023-11-01 02:27
> > > huh it looks good on a horizontal axis but i think its still pretty wonky vertically. either way this is more than exceptional thanks for all this work.
> > 
> > 
> > Check out [this footage](https://youtu.be/MkzO6DbDh0Q?t=8197) of the PS3 version being played, I've timestamped the same bomb scent area. It looks to match up to my eyes.
> > You're right though that it does look "off" but as you can see that's how it looks in the HD collection. Maybe it looked different in the PS2 original?
> 
> I think your right this might have been a difference between the HD collection and the PS2. Here is a video of the game in PCSX2, It seems to be completly static unlike the PS3 Collection.
> 
> Here is a link to the PCSX2 Footage (20:46): https://www.youtube.com/watch?v=-lEYdMRIqBA I also found this footage which follows the same behaviour as above but i cant find what platfrom its on but i think it is native PS2 (3:47): https://www.youtube.com/watch?v=xdF-LGiTsB0

It almost looks like the scent marker is contained to a bounding box. That bounding box presumably not being scaled incorrectly with the HD conversion to 16:9.

**Comment by ConnorBarr** [comment] 2023-11-01 03:07
> > > > huh it looks good on a horizontal axis but i think its still pretty wonky vertically. either way this is more than exceptional thanks for all this work.
> > > 
> > > 
> > > Check out [this footage](https://youtu.be/MkzO6DbDh0Q?t=8197) of the PS3 version being played, I've timestamped the same bomb scent area. It looks to match up to my eyes.
> > > You're right though that it does look "off" but as you can see that's how it looks in the HD collection. Maybe it looked different in the PS2 original?
> > 
> > 
> > I think your right this might have been a difference between the HD collection and the PS2. Here is a video of the game in PCSX2, It seems to be completly static unlike the PS3 Collection.
> > Here is a link to the PCSX2 Footage (20:46): https://www.youtube.com/watch?v=-lEYdMRIqBA I also found this footage which follows the same behaviour as above but i cant find what platfrom its on but i think it is native PS2 (3:47): https://www.youtube.com/watch?v=xdF-LGiTsB0
> 
> It almost looks like the scent marker is contained to a bounding box. That bounding box presumably not being scaled incorrectly with the HD conversion to 16:9.

That does sound possible but is there a way to verify? Would setting the aspect ratio to the orignal 4:3 make a difference or would the scale be off regardless?

**Comment by kite1234567** [comment] 2023-11-01 12:55
classic HD collection bugs at it again...

**Comment by Lyall** [comment] 2023-11-01 20:54
So with this being a confirmed HD collection bug is there any interest in fixing it? I'd consider the issue to be pretty minor so I probably won't do much research into unless others deemed it important enough.

**Comment by ConnorBarr** [comment] 2023-11-01 22:02
> So with this being a confirmed HD collection bug is there any interest in fixing it? I'd consider the issue to be pretty minor so I probably won't do much research into unless others deem it important enough.

I think it’s fine as it is, it’s been this way 10+ years with the HD collection and I haven’t seen any one mention it so it isn't causing any adverse effect.

It’s also technically not related to this issue as it isn’t caused by modifying the resolution, as this is the ‘intended’ behaviour even at native.

**Comment by Lyall** [comment] 2023-11-01 22:27
> > So with this being a confirmed HD collection bug is there any interest in fixing it? I'd consider the issue to be pretty minor so I probably won't do much research into unless others deem it important enough.
> 
> I think it’s fine as it is, it’s been this way for 10+ years with the HD collection and I haven’t seen any one mention it so it isn't causing any adverse effect.
> 
> It’s also technically not related to this issue as it isn’t caused by modifying the resolution, as this is the ‘intended’ behaviour even at native.

All right, will leave it as is. As for this issue overall I think it's pretty much sorted now. As always if anyone runs in to any issues related to it, feel free to open a new issue.

**Closed as completed by Lyall** 2023-11-01 22:27 UTC
Labels: MGS2
